import { Document, Page, View, Text } from '@react-pdf/renderer';
import { pdfStyles, formatPdfCents } from './styles';

export function InvoicePdf({
  orgName,
  invoice,
}: {
  orgName: string;
  invoice: {
    number: number;
    issueDate: Date;
    dueDate: Date;
    status: string;
    customerName: string;
    subtotalCents: number;
    taxCents: number;
    totalCents: number;
    amountPaidCents: number;
    notes: string | null;
    lines: { description: string; quantity: number; unitPriceCents: number; amountCents: number }[];
  };
}) {
  const balanceDueCents = invoice.totalCents - invoice.amountPaidCents;

  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <View style={pdfStyles.headerRow}>
          <Text style={pdfStyles.brand}>{orgName}</Text>
          <View style={{ alignItems: 'flex-end' }}>
            <Text style={{ fontSize: 16 }}>Invoice #{invoice.number}</Text>
            <Text style={pdfStyles.metaLabel}>{invoice.status}</Text>
          </View>
        </View>

        <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 }}>
          <View>
            <Text style={pdfStyles.metaLabel}>Billed to</Text>
            <Text style={pdfStyles.metaValue}>{invoice.customerName}</Text>
          </View>
          <View style={{ alignItems: 'flex-end' }}>
            <Text style={pdfStyles.metaLabel}>Issued</Text>
            <Text style={pdfStyles.metaValue}>{invoice.issueDate.toLocaleDateString('en-US')}</Text>
            <Text style={pdfStyles.metaLabel}>Due</Text>
            <Text style={pdfStyles.metaValue}>{invoice.dueDate.toLocaleDateString('en-US')}</Text>
          </View>
        </View>

        <View style={pdfStyles.table}>
          <View style={[pdfStyles.row, { borderColor: '#B7AD86' }]}>
            <Text style={[pdfStyles.cellLeft, pdfStyles.metaLabel]}>Description</Text>
            <Text style={[{ width: 60, textAlign: 'right' }, pdfStyles.metaLabel]}>Qty</Text>
            <Text style={[{ width: 80, textAlign: 'right' }, pdfStyles.metaLabel]}>Rate</Text>
            <Text style={[{ width: 80, textAlign: 'right' }, pdfStyles.metaLabel]}>Amount</Text>
          </View>
          {invoice.lines.map((line, i) => (
            <View style={pdfStyles.row} key={i}>
              <Text style={pdfStyles.cellLeft}>{line.description}</Text>
              <Text style={{ width: 60, textAlign: 'right' }}>{line.quantity}</Text>
              <Text style={{ width: 80, textAlign: 'right' }}>{formatPdfCents(line.unitPriceCents)}</Text>
              <Text style={{ width: 80, textAlign: 'right' }}>{formatPdfCents(line.amountCents)}</Text>
            </View>
          ))}
        </View>

        <View style={{ marginTop: 12, alignSelf: 'flex-end', width: 220 }}>
          <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 }}>
            <Text>Subtotal</Text>
            <Text>{formatPdfCents(invoice.subtotalCents)}</Text>
          </View>
          {invoice.taxCents > 0 && (
            <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 }}>
              <Text>Tax</Text>
              <Text>{formatPdfCents(invoice.taxCents)}</Text>
            </View>
          )}
          <View style={pdfStyles.totalRow}>
            <Text style={pdfStyles.totalLabel}>Total</Text>
            <Text style={pdfStyles.totalValue}>{formatPdfCents(invoice.totalCents)}</Text>
          </View>
          {invoice.amountPaidCents > 0 && (
            <>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 }}>
                <Text>Paid</Text>
                <Text>{formatPdfCents(invoice.amountPaidCents)}</Text>
              </View>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginTop: 4 }}>
                <Text style={{ fontFamily: 'Helvetica-Bold' }}>Balance due</Text>
                <Text style={{ fontFamily: 'Helvetica-Bold' }}>{formatPdfCents(balanceDueCents)}</Text>
              </View>
            </>
          )}
        </View>

        {invoice.notes && (
          <View style={{ marginTop: 20 }}>
            <Text style={pdfStyles.metaLabel}>Notes</Text>
            <Text>{invoice.notes}</Text>
          </View>
        )}

        <Text style={pdfStyles.footer}>Generated by LedgerFlow</Text>
      </Page>
    </Document>
  );
}
