import { Document, Page, View, Text } from '@react-pdf/renderer';
import { pdfStyles, formatPdfCents } from './styles';

export type StatementSection = {
  title: string;
  rows: { code?: string; name: string; amountCents: number }[];
  totalLabel?: string;
};

export function StatementPdf({
  orgName,
  reportTitle,
  rangeLabel,
  sections,
  summaryLines,
  grandTotal,
}: {
  orgName: string;
  reportTitle: string;
  rangeLabel: string;
  sections: StatementSection[];
  summaryLines?: { label: string; amountCents: number }[];
  grandTotal?: { label: string; amountCents: number };
}) {
  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <View style={pdfStyles.headerRow}>
          <Text style={pdfStyles.brand}>LedgerFlow</Text>
          <View>
            <Text style={pdfStyles.metaLabel}>{orgName}</Text>
          </View>
        </View>

        <Text style={{ fontSize: 14, marginBottom: 2 }}>{reportTitle}</Text>
        <Text style={pdfStyles.metaLabel}>{rangeLabel}</Text>

        {sections.map((section) => {
          const subtotal = section.rows.reduce((s, r) => s + r.amountCents, 0);
          return (
            <View key={section.title}>
              <Text style={pdfStyles.sectionTitle}>{section.title}</Text>
              <View style={pdfStyles.table}>
                {section.rows.map((row, i) => (
                  <View style={pdfStyles.row} key={i}>
                    {row.code !== undefined && <Text style={pdfStyles.cellCode}>{row.code}</Text>}
                    <Text style={pdfStyles.cellLeft}>{row.name}</Text>
                    <Text style={pdfStyles.cellRight}>{formatPdfCents(row.amountCents)}</Text>
                  </View>
                ))}
              </View>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginTop: 4 }}>
                <Text style={{ fontSize: 9, color: '#6B7A70' }}>
                  {section.totalLabel ?? `Total ${section.title.toLowerCase()}`}
                </Text>
                <Text style={{ fontSize: 9 }}>{formatPdfCents(subtotal)}</Text>
              </View>
            </View>
          );
        })}

        {summaryLines && (
          <View style={{ marginTop: 12 }}>
            {summaryLines.map((line) => (
              <View
                key={line.label}
                style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 }}
              >
                <Text>{line.label}</Text>
                <Text>{formatPdfCents(line.amountCents)}</Text>
              </View>
            ))}
          </View>
        )}

        {grandTotal && (
          <View style={pdfStyles.totalRow}>
            <Text style={pdfStyles.totalLabel}>{grandTotal.label}</Text>
            <Text style={pdfStyles.totalValue}>{formatPdfCents(grandTotal.amountCents)}</Text>
          </View>
        )}

        <Text style={pdfStyles.footer}>
          Generated by LedgerFlow on {new Date().toLocaleDateString('en-US')}
        </Text>
      </Page>
    </Document>
  );
}
